version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
      - db

  backend:
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file:
      - .env
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
  proxy:
    env_file:
      - .env
    image: traefik:v3.0
    command: --providers.docker
    ports:
      - ${APP_PORT:-10000}:10000
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  mysql-data:
