version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - backend
    profiles:
      - apps

  backend:
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
      REDIS_URL: redis://redis:6379/0
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 urlShortener.wsgi:application"
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    profiles:
      - apps

  celery:
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/2
    build:
      context: ./backend/
      dockerfile: Dockerfile
    depends_on:
      - redis
      - backend
    command: celery -A urlShortener worker --loglevel=info
    profiles:
      - apps

  db:
    env_file:
      - .env
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # Initialization scripts
    ports:
      - ${DB_PORT}:3306

  redis:
    env_file:
      - .env
    image: redis:6
    restart: always
    ports:
      - ${REDIS_PORT-:6379}:6379

  proxy:
    env_file:
      - .env
    image: traefik:v3.0
    command: --providers.docker
    ports:
      - ${APP_PORT:-10000}:10000
    volumes:
      - ./traefik-dev.toml:/etc/traefik/traefik.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  mysql-data:
