version: '3.8'

services:
  db:
    env_file:
      - .env
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d # Initialization scripts
    ports:
      - ${DB_PORT}:3306
  proxy:
    env_file:
      - .env
    image: traefik:v3.0
    command: --providers.docker
    ports:
      - ${APP_PORT:-10000}:10000
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml

volumes:
  mysql-data:
