defaultEntryPoints = ["http"]

[log]
level = "INFO"

[api]
dashboard = true

[accessLog]


[providers]
providersThrottleDuration = 10
[providers.file]
filename = "traefik.toml"
directory = "/etc/traefik/"
watch = true


[entryPoints]
[entryPoints.web]
address = ":10000"
# use this in a secure reverse proxy environment
[entryPoints.web.forwardedHeaders]
insecure = true

[http.routers]

[http.routers.django]
service = "django"
rule = "PathPrefix(`/accounts`) || PathPrefix(`/_allauth`) || PathPrefix(`/shortUrl`)"
entrypoints = ["web"]


[http.routers.react]
service = "react"
rule = "PathPrefix(`/`)"
entrypoints = ["web"]

[http.services]
[http.services.react.loadBalancer]
[[http.services.react.loadBalancer.servers]]
url = "http://frontend:80"
[http.services.django.loadBalancer]
[[http.services.django.loadBalancer.servers]]
url = "http://backend:8000"
