# Generated by Django 5.1.4 on 2024-12-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlog',
            name='short_url',
            field=models.ForeignKey(db_column='short_url', on_delete=django.db.models.deletion.CASCADE, to='shortener.url', to_field='short_url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
